export const config = {
    defaultLanguage: "it",
    MONGO_URI: "mongodb://localhost:27017",
    strings: {
        en: {
            HEADLINE_TITLE: "Room Booking Calendar",
            HEADLINE_DESC: "Manage your room reservations efficiently",
            ROOMS_LABEL: "Rooms",
            ROOM_LEGEND_LABEL: "Room Legend",
            NEW_BOOKING_ACTION: "New Booking",
            WEEK_SUNDAY_SHORT:    "Sun",
            WEEK_MONDAY_SHORT:    "Mon",
            WEEK_TUESDAY_SHORT:   "Tue",
            WEEK_WEDNESDAY_SHORT: "Wed",
            WEEK_THURSDAY_SHORT:  "Thu",
            WEEK_FRIDAY_SHORT:    "Fri",
            WEEK_SATURDAY_SHORT:  "Sat",
            TODAY_LABEL: "Today",
            CURRENT_MONTH_BOOKINGS: "Current Month Bookings",
            NO_BOOKINGS_AVAILABLE: "No bookings for this month",
            DAYS_LABEL: "days",
            DAY_LABEL: "day",
            MODAL_CREATE_NEW_BOOKING: "Create New Booking",
            MODAL_SELECT_DATES: "Selected Dates",
            MODAL_ROOM_ASSIGNMENT: "Room Assignment",
            MODAL_SELECT_ROOM_INPUT: "Select a room...",
            MODAL_CUSTOMER_NAME: "Customer Name",
            MODAL_ENTER_CUSTOMER_NAME_INPUT: "Enter customer name",
            MODAL_CUSTOMER_EMAIL: "Customer Email",
            MODAL_SPECIAL_NOTES: "Special Notes",
            MODAL_SPECIAL_NOTES_INPUT: "Any special requirements or notes...",
            MODAL_DATE_CONFLICT: "This room is already booked for some of the selected dates.",
            MODAL_CREATION_FAILED: "Failed to create booking",
            MODAL_CREATE_BOOKING_BUTTON: "Create Booking",
            MODAL_CANCEL_BUTTON: "Cancel",
            MODAL_PENDING_CREATING: "Creating...",
            MODAL_BOOKING_CREATED_TITLE: "Success",
            MODAL_BOOKING_CREATED: "Booking created successfully!",
            MODAL_BOOKING_ERROR_TITLE: "Error",
            MODAL_BOOKING_ERROR: "Please fill in all required fields",
        },
        it: {
            HEADLINE_TITLE: "Calendario Prenotazioni Camere",
            HEADLINE_DESC: "Gestisci le prenotazioni delle camere in modo efficiente",
            ROOMS_LABEL: "Camere",
            ROOM_LEGEND_LABEL: "Legenda stanze",
            NEW_BOOKING_ACTION: "Nuova Prenotazione",
            WEEK_SUNDAY_SHORT:    "Dom",
            WEEK_MONDAY_SHORT:    "Lun",
            WEEK_TUESDAY_SHORT:   "Mar",
            WEEK_WEDNESDAY_SHORT: "Mer",
            WEEK_THURSDAY_SHORT:  "Gio",
            WEEK_FRIDAY_SHORT:    "Ven",
            WEEK_SATURDAY_SHORT:  "Sab",
            TODAY_LABEL: "Oggi",
            CURRENT_MONTH_BOOKINGS: "Prenotazioni del Mese Corrente",
            NO_BOOKINGS_AVAILABLE: "Nessuna prenotazione per questo mese",
            DAYS_LABEL: "giorni",
            DAY_LABEL: "giorno",
            MODAL_CREATE_NEW_BOOKING: "Crea Nuova Prenotazione",
            MODAL_SELECT_DATES: "Date Selezionate",
            MODAL_ROOM_ASSIGNMENT: "Assegnazione Camera",
            MODAL_SELECT_ROOM_INPUT: "Seleziona una camera...",
            MODAL_CUSTOMER_NAME: "Nome Cliente",
            MODAL_ENTER_CUSTOMER_NAME_INPUT: "Inserisci il nome del cliente",
            MODAL_CUSTOMER_EMAIL: "Email Cliente",
            MODAL_SPECIAL_NOTES: "Note Speciali",
            MODAL_SPECIAL_NOTES_INPUT: "Eventuali richieste o note speciali...",
            MODAL_DATE_CONFLICT: "Questa stanza è già stata prenotata per le date selezionate.",
            MODAL_CREATE_BOOKING_BUTTON: "Crea Prenotazione",
            MODAL_CANCEL_BUTTON: "Annulla",
            MODAL_PENDING_CREATING: "Creazione in corso...",
            
            MODAL_CREATION_FAILED: "Creazione del booking fallita",
            MODAL_BOOKING_CREATED_TITLE: "Operazione completata",
            MODAL_BOOKING_CREATED: "Booking creato con successo!",
            MODAL_BOOKING_ERROR_TITLE: "Errore",
            MODAL_BOOKING_ERROR: "Perfavore riempi tutti i campi",

        }
    }
};